### PR TITLE
Convert from a raw C extension to Cython and flesh out Module attributes.

### PR DESCRIPTION
**Pull request by wking**
I want to get modinfo-style output for a particular module (especially staging and vermagic) from Python, so I thought this would be the module to use.  Unfortunately, I'm running Python 3, and the trunk module is written for Python 2.  I took a peak at upgrading to Python 3, but quite a bit of the C extension boilerplate has changed, so I gave up and just translated python-kmod into Cython.  This patch series makes that conversion, and fleshes out a new Module class with a number of attributes.  I also touched up the packaging a bit (setup.py, MANIFEST.in).  Now you can do things like:

```
>>> import kmod
>>> k = kmod.Kmod()
>>> for module in k.loaded():
...     for attribute in ['name', 'info']:
...         print('{}: {}'.format(attribute, getattr(module, attribute)))
name: ntfs
info: {'description': 'NTFS 1.2/3.x driver - Copyright (c) 2001-2011 Anton Altaparmakov and Tuxera Inc.', 'license': 'GPL', …}
…
```

This should close issue #1.

### CODE REVIEW

**Comment by agrover** [comment]
hey cool, I've been wanting to learn/use Cython! Will take a closer look tomorrow morning.

**Comment by agrover** [comment]
Any chance we can cut down on the number of files with only 1-5 actual lines of code in them? Also please use the license header that references gnu.org/licenses rather than their physical address.

But this is looking really good. And it supports Python 3, how cool is that.

**Comment by wking** [comment]
On Fri, Oct 19, 2012 at 10:42:53AM -0700, Andy Grover wrote:

> Any chance we can cut down on the number of files with only 1-5
> actual lines of code in them?

The *.pxd files are usually pretty brief, but Cython needs them to
share C interfaces between modules.  We can't put KmodError into
**init** without creating an **init** ↔ kmod import cycle.  version
has to be separate so setup.py can import it before any of the Cython
stuff has been compiled.  In general, I think things will either stay
how they are, or get lumped into a single kitchen sink module.

I like things split up, because when I'm reading about the Kmod
processing (which I care about), I don't want to be distracted by the
Module implementation (which I don't care about).  I'm theoretically
open to restructuring though, if you have different groupings youd
like to propose.

> Also please use the license header that references gnu.org/licenses
> rather than their physical address.

No problem.  I just copied the blurb from the top of libkmod.c and
added myself.  I'd like to plug my own solution here [1](http://pypi.python.org/pypi/update-copyright/), since
maintaining copyright blurbs by hand either feels tedious or
self-aggrandizing ;).

## 

This email may be signed or encrypted with GnuPG (http://www.gnupg.org).
For more information, see http://en.wikipedia.org/wiki/Pretty_Good_Privacy

**Comment by wking** [comment]
> I'd like to plug my own solution here [1](https://github.com/wking/python-kmod/tree/copyright), since maintaining copyright blurbs by hand either feels tedious or self-aggrandizing ;).

I've pushed and [example branch](https://github.com/wking/python-kmod/tree/copyright) to show how this would work.

**Comment by agrover** [comment]
Proposed copyright updates look fine. I await your pull req, and then will likely release a 0.9, and then 1.0 after some more testing.

Much thanks for this sizable contribution (complete rewrite, really.). If you have a longer-term desire to hack on and improve (maintain?) this code, let me know and we can talk.

**Comment by wking** [comment]
On Mon, Oct 22, 2012 at 11:27:35AM -0700, Andy Grover wrote:

> Proposed copyright updates look fine. I await your pull req,

Submitted.

> Much thanks for this sizable contribution (complete rewrite,
> really.).

No problem, thanks for accepting my itch-scratching.

> If you have a longer-term desire to hack on and improve (maintain?)
> this code, let me know and we can talk.

I don't have further needs for this package, so I probably won't be
much help.  That said, if the underlying kmod library makes some
incompatible change and breaks my modinfo, I'll certainly send over
another pull request ;).

## 

This email may be signed or encrypted with GnuPG (http://www.gnupg.org).
For more information, see http://en.wikipedia.org/wiki/Pretty_Good_Privacy

**Pull request merged**
