### PR TITLE
Issue #15

### PR DESCRIPTION
**Pull request by grzn**

### CODE REVIEW

**Comment by grzn** [comment]
still doesn't work, i'll update when it does

**Comment by agrover** [comment]
thanks for working through this issue.

**Comment by grzn** [comment]
and thank you for the very quick responses! (not less important)

**Comment by grzn** [comment]
when are you going to release 0.9.2 (with this pull request)?

**Comment by grzn** [comment]
one last thing coming up :)

**Comment by agrover** [comment]
ok :)

**Pull request merged**
